name: yt-summarizer

services:
  yt-summarizer:
    container_name: yt-summarizer
    hostname: yt-summarizer
    networks:
      - yt-summarizer
    build: .
    ports:
      - "17430:8080"
    environment:
      - PORT=8080
      - OLLAMA_BASE_URL=http://host.docker.internal:11434/api
    volumes:
      - ./transcripts:/app/transcripts
      - ./cookies/cookies.txt:/data/cookies/cookies.txt
networks:
  yt-summarizer:
    name: yt-summarizer
